### ISSUE TITLE
Error in "bg"

### ISSUE THREAD

**Issue by omizonly** [ppriyank/Pytorch-CustomDataset-FasterRCNN#3]
loading from scratch 

0
#########################
Training epoch 0
Traceback (most recent call last):

  File "/home/nd/Osman/Pytorch-CustomDataset-FasterRCNN-master/main.py", line 516, in <module>
    train(i)

  File "/home/nd/Osman/Pytorch-CustomDataset-FasterRCNN-master/main.py", line 282, in train
    for i,(image, boxes, labels , temp, num_pos) in enumerate(train_loader):

  File "/home/nd/anaconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()

  File "/home/nd/anaconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1085, in _next_data
    return self._process_data(data)

  File "/home/nd/anaconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
    data.reraise()

  File "/home/nd/anaconda3/lib/python3.8/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)

TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/nd/anaconda3/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/nd/anaconda3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/nd/anaconda3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/nd/Osman/Pytorch-CustomDataset-FasterRCNN-master/dataset.py", line 60, in __getitem__
    y_is_box_label, y_rpn_regr, num_pos  = self.rpm.calc_rpn(boxes , labels,  image_resize_size=self.image_resize_size)
  File "/home/nd/Osman/Pytorch-CustomDataset-FasterRCNN-master/tools.py", line 146, in calc_rpn
    if self.rev_label_map[labels[bbox_num]] != 'bg':
TypeError: unhashable type: 'list'

**Comment by ppriyank** [comment]
The error is originated here : https://github.com/ppriyank/Pytorch-CustomDataset-FasterRCNN/blob/master/tools.py#L146 
Can you set up an pdb there? 

at line 145, write: 
```
import pdb
pdb.set_trace() 
```
and paste the output from 

```
print(self.rev_label_map)
print(labels)
print(bbox_num)
```
