### ISSUE TITLE
Can't run with custom data

### ISSUE THREAD

**Issue by Chethan-Babu-stack** [ppriyank/Pytorch-CustomDataset-FasterRCNN#4]
I have followed steps to create TRAIN_images.json, TRAIN_objects.json, TEST_images.json, TEST_objects.

When I run the main.py, I get the following error.
loading from scratch 

Training epoch 0

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Chethan\anaconda3\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\Chethan\anaconda3\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Users\Chethan\anaconda3\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\Chethan\anaconda3\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Users\Chethan\anaconda3\lib\runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\Chethan\anaconda3\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\Chethan\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Chethan\Desktop\Fraunhofer_IIS_2021\BBox_Segmentation\Pytorch-CustomDataset-FasterRCNN-master\main.py", line 12, in <module>
    from model import Model_RPN , Classifier
ModuleNotFoundError: No module named 'model'

Suggest what I could do. Thanks.

**Comment by ppriyank** [comment]
The actual error is : 
"File "C:\Users\Chethan\Desktop\Fraunhofer_IIS_2021\BBox_Segmentation\Pytorch-CustomDataset-FasterRCNN-master\main.py", line 12, in
from model import Model_RPN , Classifier
ModuleNotFoundError: No module named 'model'"

which means model.py or model folder not found. 

In our case, it means model.py, check you main.py and model.py are in the same folder.

**Comment by Chethan-Babu-stack** [comment]
They are in the same folder.

The issue come here "for i,(image, boxes, labels , temp, num_pos) in enumerate(train_loader):"

**Comment by Chethan-Babu-stack** [comment]
I was running the code earlier in Spyder. Now when I run in the command prompt, it shows this error:

loading from scratch




Training epoch 0
loading from scratch




Training epoch 0
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Chethan\Anaconda3\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\Chethan\Anaconda3\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Users\Chethan\Anaconda3\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\Chethan\Anaconda3\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Users\Chethan\Anaconda3\lib\runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\Chethan\Anaconda3\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\Chethan\Anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Chethan\Desktop\Fraunhofer_IIS_2021\BBox_Segmentation\Pytorch-CustomDataset-FasterRCNN-master\main.py", line 512, in <module>
    train(i)
  File "C:\Users\Chethan\Desktop\Fraunhofer_IIS_2021\BBox_Segmentation\Pytorch-CustomDataset-FasterRCNN-master\main.py", line 282, in train
    for i,(image, boxes, labels , temp, num_pos) in enumerate(train_loader):
  File "C:\Users\Chethan\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 352, in __iter__
    return self._get_iterator()
  File "C:\Users\Chethan\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 294, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Users\Chethan\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 801, in __init__
    w.start()
  File "C:\Users\Chethan\Anaconda3\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\Chethan\Anaconda3\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\Chethan\Anaconda3\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\Users\Chethan\Anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\Chethan\Anaconda3\lib\multiprocessing\spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\Chethan\Anaconda3\lib\multiprocessing\spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
